"""cloudflared ingress and Cloudflare Access.

**The routing trick that makes one frontend image serve everyone.**
cloudflared matches on hostname *and path*, so `/api/*` goes straight to the
user's native backend and everything else to their frontend container:

    - hostname: alice.facet.example
      path: ^/api/
      service: http://127.0.0.1:8101      # native backend, agy reachable
    - hostname: alice.facet.example
      service: http://127.0.0.1:3101      # frontend container

Without this the frontend would have to proxy `/api`, and Next bakes rewrite
destinations into routes-manifest.json at *build* time — meaning a separate
image build per user, since each backend listens on a different port. Letting
the tunnel do the routing means no per-user address is baked in anywhere and
one image serves everybody.

**Access is the authentication.** A policy per hostname naming one email
address. That is why no login exists anywhere in Facet: Access already
answers "who is this", and a second identity system behind it would be
strictly worse than the one already there.

Nothing here is published to any interface — every service target is
loopback. The tunnel is the only way in.
"""

import json
import os
import urllib.error
import urllib.request
from pathlib import Path

CF_API = "https://api.cloudflare.com/client/v4"

TUNNEL_CONFIG = Path(
    os.environ.get("FACET_TUNNEL_CONFIG", "").strip() or "/etc/cloudflared/config.yml"
)
BASE_DOMAIN = os.environ.get("FACET_BASE_DOMAIN", "").strip() or "facet.example"
TUNNEL_ID = os.environ.get("FACET_TUNNEL_ID", "").strip()
CF_ACCOUNT_ID = os.environ.get("CF_ACCOUNT_ID", "").strip()
CF_API_TOKEN = os.environ.get("CF_API_TOKEN", "").strip()

# Access sessions last this long before re-authenticating. A day is the
# balance between not nagging people and not leaving a laptop authenticated
# for a month.
SESSION_DURATION = "24h"


# Everyone shares one hostname. The app tells people apart from the Access
# identity header, not from the address they typed.
#
# Per-user subdomains were the previous design and could not work on a domain
# like facet.nivil.dpdns.org: Cloudflare's free Universal SSL covers a single
# level of subdomain, so alice.facet.nivil.dpdns.org has no certificate.
# A function, not a constant copied from BASE_DOMAIN at import. The copy was
# stale the moment anything reassigned BASE_DOMAIN -- the same late-binding
# trap that paths.py exists to avoid.
def facet_hostname() -> str:
    return BASE_DOMAIN

# The ports the one shared instance listens on.
BACKEND_PORT = int(os.environ.get("FACET_BACKEND_PORT", "").strip() or 8000)
FRONTEND_PORT = int(os.environ.get("FACET_FRONTEND_PORT", "").strip() or 3000)


def hostname_for(_slug: str | None = None) -> str:
    """The Facet hostname. The argument is ignored and kept so callers that
    still pass a slug get the right answer rather than a TypeError."""
    return facet_hostname()


# ----------------------------------------------------------------- ingress

def ingress_rules(users: list[dict] | None = None) -> list[dict]:
    """The ingress list: two rules and a catch-all, whoever the users are.

    It no longer depends on the user table at all — one instance serves
    everyone, so adding a person changes nothing here. `users` is accepted
    and ignored so existing callers keep working.

    Order matters. The `/api` rule must precede the catch-all for the same
    hostname or the frontend swallows every API call.

    Both services are loopback, and that is load-bearing rather than tidy:
    the app trusts the Access identity header precisely because cloudflared
    on this host is the only thing that can reach these ports.
    """
    return [
        {
            "hostname": facet_hostname(),
            "path": "^/api/",
            "service": f"http://127.0.0.1:{BACKEND_PORT}",
        },
        {
            "hostname": facet_hostname(),
            "service": f"http://127.0.0.1:{FRONTEND_PORT}",
        },
        # cloudflared requires a terminating catch-all; without it the config
        # is rejected outright.
        {"service": "http_status:404"},
    ]


def render_tunnel_config(users: list[dict] | None = None,
                         tunnel_id: str | None = None) -> str:
    """The whole cloudflared config file, as YAML we emit by hand.

    Hand-rolled rather than pulling in PyYAML: the structure is a fixed list
    of two-or-three-key mappings, and this keeps the host install to what the
    app already needs.
    """
    tunnel = tunnel_id or TUNNEL_ID or "<TUNNEL-ID>"
    lines = [
        "# Generated by Facet's control plane. Do not hand-edit.",
        "# One hostname for everyone; adding a user does not change this file.",
        f"tunnel: {tunnel}",
        f"credentials-file: /etc/cloudflared/{tunnel}.json",
        "",
        "ingress:",
    ]
    for rule in ingress_rules(users):
        first = True
        for key in ("hostname", "path", "service"):
            if key not in rule:
                continue
            prefix = "  - " if first else "    "
            lines.append(f"{prefix}{key}: {rule[key]}")
            first = False
    return "\n".join(lines) + "\n"


def write_tunnel_config(users: list[dict] | None = None,
                        path: Path | None = None) -> Path:
    target = path or TUNNEL_CONFIG
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render_tunnel_config(users), encoding="utf-8")
    return target


# ------------------------------------------------------------------ access

def access_app_payload(emails: list[str]) -> dict:
    """The one Access application, allowing every registered address."""
    return {
        "name": "Facet",
        "domain": facet_hostname(),
        "type": "self_hosted",
        "session_duration": SESSION_DURATION,
        # The tunnel already means nothing is reachable except through
        # Cloudflare; these keep the browser session honest too.
        "http_only_cookie_attribute": True,
        "same_site_cookie_attribute": "lax",
        "policies": [access_policy_payload(emails)],
    }


def access_policy_payload(emails: list[str]) -> dict:
    """Allow exactly these addresses. Not a domain, not a group.

    Access decides *whether* someone gets in; Facet decides *whose data they
    see*, by matching the address Access reports against its own user table.
    Both must say yes, so an address listed here but not registered in Facet
    gets "you have no Facet on this host" rather than somebody else's tracker.

    Listing a domain (`@gmail.com`) instead of addresses would let every Gmail
    user in the world past the only authentication this deployment has.
    """
    return {
        "name": "Facet users",
        "decision": "allow",
        "include": [{"email": {"email": email}} for email in sorted(set(emails))],
    }


def _api(method: str, path: str, body: dict | None = None) -> dict:
    if not CF_API_TOKEN or not CF_ACCOUNT_ID:
        raise RuntimeError("CF_API_TOKEN and CF_ACCOUNT_ID are not set")

    request = urllib.request.Request(
        f"{CF_API}/accounts/{CF_ACCOUNT_ID}{path}",
        method=method,
        data=json.dumps(body).encode() if body is not None else None,
        headers={
            "Authorization": f"Bearer {CF_API_TOKEN}",
            "Content-Type": "application/json",
        },
    )
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            return json.loads(response.read())
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")[:400]
        raise RuntimeError(f"Cloudflare API {exc.code}: {detail}") from exc


def create_access_app(emails: list[str]) -> dict:
    return _api("POST", "/access/apps", access_app_payload(emails))


def update_access_app(app_id: str, emails: list[str]) -> dict:
    """Rewrite the policy in place, from the full user list.

    Rewritten rather than appended for the same reason the ingress file is:
    an incremental scheme drifts as soon as one edit half-fails, and drift in
    an allow-list is either somebody locked out or somebody who should have
    been removed still getting in.
    """
    return _api("PUT", f"/access/apps/{app_id}", access_app_payload(emails))


def delete_access_app(app_id: str) -> dict:
    return _api("DELETE", f"/access/apps/{app_id}")


def find_access_app(_slug: str | None = None) -> dict | None:
    """The one Facet application, if it exists yet."""
    for app in _api("GET", "/access/apps").get("result", []):
        if app.get("domain") == facet_hostname():
            return app
    return None


def sync_access_app(emails: list[str]) -> str:
    """Make the Access policy match the registered users. Idempotent."""
    existing = find_access_app()
    if existing is None:
        create_access_app(emails)
        return f"created the Facet application for {len(emails)} address(es)"
    update_access_app(existing["id"], emails)
    return f"updated the Facet policy to {len(emails)} address(es)"


def manual_instructions(emails: list[str]) -> str:
    """What to do by hand when the API isn't configured.

    Manual mode is the default (PLAN.md D8): an API token with Access-write
    is a real capability, and this is now a single edit rather than one per
    user.
    """
    listed = "\n".join(f"        {email}" for email in sorted(set(emails)))
    return (
        f"1. DNS (once): CNAME {facet_hostname()} -> <tunnel-id>.cfargotunnel.com\n"
        f"   Proxied (orange). Grey-cloud bypasses Access entirely.\n"
        f"2. Zero Trust > Access > Applications — one self-hosted app:\n"
        f"   Name: Facet\n"
        f"   Domain: {facet_hostname()}\n"
        f"   Session duration: {SESSION_DURATION}\n"
        f"3. Its policy: Allow, Include > Emails:\n"
        f"{listed}\n"
        f"   Individual addresses, never a whole domain — Access is the only\n"
        f"   authentication this deployment has.\n"
        f"4. Reload the tunnel: systemctl reload cloudflared"
    )


def demo() -> None:
    """Self-check:  backend/.venv/bin/python -m control.cloudflare

    Pure config generation. No network calls — these have to be right for a
    Cloudflare account this was never run against.
    """
    global BASE_DOMAIN
    BASE_DOMAIN = "facet.example"

    users = [
        {"id": 1, "slug": "alice", "email": "alice@example.com"},
        {"id": 2, "slug": "bob", "email": "bob@example.com"},
    ]
    rules = ingress_rules(users)

    # Two rules and a catch-all, regardless of how many users there are.
    # This is the whole point of the single-instance design: adding a person
    # changes nothing about the routing.
    assert len(rules) == 3, rules
    assert rules == ingress_rules([]), "ingress must not depend on the user table"
    assert rules == ingress_rules(users * 5), "ingress must not grow with users"
    assert rules[-1] == {"service": "http_status:404"}, rules[-1]

    # The /api rule must come first, or the frontend swallows every API call.
    # This is the single most important ordering in the file.
    assert rules[0]["hostname"] == "facet.example"
    assert rules[0]["path"] == "^/api/" and str(BACKEND_PORT) in rules[0]["service"]
    assert "path" not in rules[1] and str(FRONTEND_PORT) in rules[1]["service"]

    # Every target is loopback. The app trusts the Access identity header
    # only because cloudflared on this host is the sole thing that can reach
    # these ports; a public bind turns that header into an auth bypass.
    http_rules = [r for r in rules if r["service"].startswith("http://")]
    assert all("127.0.0.1" in r["service"] for r in http_rules), rules
    assert len({r["service"] for r in http_rules}) == len(http_rules), rules

    config = render_tunnel_config(users, tunnel_id="abc-123")
    assert "tunnel: abc-123" in config
    assert config.count("  - hostname:") == 2, config
    assert config.rstrip().endswith("- service: http_status:404"), config
    # The generated YAML must actually parse as the structure intended.
    for line in config.splitlines():
        if line.startswith("  - ") or line.startswith("    "):
            assert ": " in line, f"malformed line: {line!r}"

    # Removing a user does not touch the tunnel at all.
    assert render_tunnel_config(users[:1], "abc-123") == config

    # ------------------------------------------------------------- access
    emails = [u["email"] for u in users]
    app = access_app_payload(emails)
    assert app["domain"] == "facet.example"
    assert app["type"] == "self_hosted"
    assert app["http_only_cookie_attribute"] is True

    policy = app["policies"][0]
    assert policy["decision"] == "allow"
    # Every registered address, listed individually. A domain-wide include
    # would let every Gmail user in the world past the only authentication
    # this deployment has.
    assert policy["include"] == [
        {"email": {"email": "alice@example.com"}},
        {"email": {"email": "bob@example.com"}},
    ], policy
    assert all("email" in entry for entry in policy["include"]), policy
    assert not any("domain" in entry for entry in policy["include"]), policy

    # Duplicates collapse rather than producing a policy with repeats.
    assert access_policy_payload(["a@x.com", "a@x.com"])["include"] == [
        {"email": {"email": "a@x.com"}}
    ]

    text = manual_instructions(emails)
    for expected in ("facet.example", "cfargotunnel.com", "alice@example.com",
                     "bob@example.com", "reload cloudflared"):
        assert expected in text, expected

    print("control.cloudflare: all checks passed (one hostname, one policy)")


if __name__ == "__main__":
    demo()
