"""cloudflared ingress and Cloudflare Access.

**The routing trick that makes one frontend image serve everyone.**
cloudflared matches on hostname *and path*, so `/api/*` goes straight to the
user's native backend and everything else to their frontend container:

    - hostname: alice.facet.example
      path: ^/api/
      service: http://127.0.0.1:8101      # native backend, agy reachable
    - hostname: alice.facet.example
      service: http://127.0.0.1:3101      # frontend container

Without this the frontend would have to proxy `/api`, and Next bakes rewrite
destinations into routes-manifest.json at *build* time — meaning a separate
image build per user, since each backend listens on a different port. Letting
the tunnel do the routing means no per-user address is baked in anywhere and
one image serves everybody.

**Access is the authentication.** A policy per hostname naming one email
address. That is why no login exists anywhere in Facet: Access already
answers "who is this", and a second identity system behind it would be
strictly worse than the one already there.

Nothing here is published to any interface — every service target is
loopback. The tunnel is the only way in.
"""

import json
import os
import urllib.error
import urllib.request
from pathlib import Path

CF_API = "https://api.cloudflare.com/client/v4"

TUNNEL_CONFIG = Path(
    os.environ.get("FACET_TUNNEL_CONFIG", "").strip() or "/etc/cloudflared/config.yml"
)
BASE_DOMAIN = os.environ.get("FACET_BASE_DOMAIN", "").strip() or "facet.example"
TUNNEL_ID = os.environ.get("FACET_TUNNEL_ID", "").strip()
CF_ACCOUNT_ID = os.environ.get("CF_ACCOUNT_ID", "").strip()
CF_API_TOKEN = os.environ.get("CF_API_TOKEN", "").strip()

# Access sessions last this long before re-authenticating. A day is the
# balance between not nagging people and not leaving a laptop authenticated
# for a month.
SESSION_DURATION = "24h"


def hostname_for(slug: str) -> str:
    return f"{slug}.{BASE_DOMAIN}"


# ----------------------------------------------------------------- ingress

def ingress_rules(users: list[dict]) -> list[dict]:
    """The full ingress list, rebuilt from the user table every time.

    Regenerated rather than patched: an append-and-remove scheme drifts the
    moment one edit fails halfway, and drift here means a hostname pointing
    at the wrong port — which is one person's Facet being served to another.
    The user table is the truth; this is a projection of it.

    Order matters. The `/api` rule must precede the catch-all for the same
    hostname or the frontend swallows every API call.
    """
    rules: list[dict] = []
    for user in sorted(users, key=lambda u: u["id"]):
        host = hostname_for(user["slug"])
        rules.append({
            "hostname": host,
            "path": "^/api/",
            "service": f"http://127.0.0.1:{user['api_port']}",
        })
        rules.append({
            "hostname": host,
            "service": f"http://127.0.0.1:{user['web_port']}",
        })
    # cloudflared requires a terminating catch-all; without it the config is
    # rejected outright.
    rules.append({"service": "http_status:404"})
    return rules


def render_tunnel_config(users: list[dict], tunnel_id: str | None = None) -> str:
    """The whole cloudflared config file, as YAML we emit by hand.

    Hand-rolled rather than pulling in PyYAML: the structure is a fixed list
    of two-or-three-key mappings, and this keeps the host install to what the
    app already needs.
    """
    tunnel = tunnel_id or TUNNEL_ID or "<TUNNEL-ID>"
    lines = [
        "# Generated by Facet's control plane. Do not hand-edit —",
        "# it is rebuilt from the user table whenever a user changes.",
        f"tunnel: {tunnel}",
        f"credentials-file: /etc/cloudflared/{tunnel}.json",
        "",
        "ingress:",
    ]
    for rule in ingress_rules(users):
        first = True
        for key in ("hostname", "path", "service"):
            if key not in rule:
                continue
            prefix = "  - " if first else "    "
            lines.append(f"{prefix}{key}: {rule[key]}")
            first = False
    return "\n".join(lines) + "\n"


def write_tunnel_config(users: list[dict], path: Path | None = None) -> Path:
    target = path or TUNNEL_CONFIG
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render_tunnel_config(users), encoding="utf-8")
    return target


# ------------------------------------------------------------------ access

def access_app_payload(slug: str, email: str) -> dict:
    """The Access application for one user's hostname."""
    return {
        "name": f"Facet — {slug}",
        "domain": hostname_for(slug),
        "type": "self_hosted",
        "session_duration": SESSION_DURATION,
        # The tunnel already means nothing is reachable except through
        # Cloudflare; these keep the browser session honest too.
        "http_only_cookie_attribute": True,
        "same_site_cookie_attribute": "lax",
        "policies": [access_policy_payload(email)],
    }


def access_policy_payload(email: str) -> dict:
    """Allow exactly one address. Not a domain, not a group.

    Each hostname serves one person's career record, so the policy that
    matches the data is a policy of one. A domain-wide rule would let every
    colleague reach every instance.
    """
    return {
        "name": f"Only {email}",
        "decision": "allow",
        "include": [{"email": {"email": email}}],
    }


def _api(method: str, path: str, body: dict | None = None) -> dict:
    if not CF_API_TOKEN or not CF_ACCOUNT_ID:
        raise RuntimeError("CF_API_TOKEN and CF_ACCOUNT_ID are not set")

    request = urllib.request.Request(
        f"{CF_API}/accounts/{CF_ACCOUNT_ID}{path}",
        method=method,
        data=json.dumps(body).encode() if body is not None else None,
        headers={
            "Authorization": f"Bearer {CF_API_TOKEN}",
            "Content-Type": "application/json",
        },
    )
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            return json.loads(response.read())
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")[:400]
        raise RuntimeError(f"Cloudflare API {exc.code}: {detail}") from exc


def create_access_app(slug: str, email: str) -> dict:
    return _api("POST", "/access/apps", access_app_payload(slug, email))


def delete_access_app(app_id: str) -> dict:
    return _api("DELETE", f"/access/apps/{app_id}")


def find_access_app(slug: str) -> dict | None:
    host = hostname_for(slug)
    for app in _api("GET", "/access/apps").get("result", []):
        if app.get("domain") == host:
            return app
    return None


def manual_instructions(slug: str, email: str) -> str:
    """What to do by hand when the API isn't configured.

    Manual mode is the default (PLAN.md D8): an API token with Access-write
    is a real capability, and two minutes per user is cheap at this scale.
    """
    host = hostname_for(slug)
    return (
        f"1. DNS: CNAME {host} -> <tunnel-id>.cfargotunnel.com (proxied)\n"
        f"   A wildcard *.{BASE_DOMAIN} covers every user at once.\n"
        f"2. Zero Trust > Access > Applications > Add > Self-hosted\n"
        f"   Name: Facet - {slug}\n"
        f"   Domain: {host}\n"
        f"   Session duration: {SESSION_DURATION}\n"
        f"3. Policy: Allow, Include > Emails > {email}\n"
        f"   One address, not a domain — this hostname serves one person's\n"
        f"   career record.\n"
        f"4. Reload the tunnel: systemctl reload cloudflared"
    )


def demo() -> None:
    """Self-check:  backend/.venv/bin/python -m control.cloudflare

    Pure config generation. No network calls — these have to be right for a
    Cloudflare account this was never run against.
    """
    global BASE_DOMAIN
    BASE_DOMAIN = "facet.example"

    users = [
        {"id": 1, "slug": "alice", "web_port": 3101, "api_port": 8101},
        {"id": 2, "slug": "bob", "web_port": 3102, "api_port": 8102},
    ]
    rules = ingress_rules(users)

    # Two rules per user plus one terminating catch-all.
    assert len(rules) == 5, rules
    assert rules[-1] == {"service": "http_status:404"}, rules[-1]

    # The /api rule must come first for a hostname, or the frontend swallows
    # every API call. This is the single most important ordering in the file.
    alice = [r for r in rules if r.get("hostname") == "alice.facet.example"]
    assert alice[0]["path"] == "^/api/" and "8101" in alice[0]["service"], alice
    assert "path" not in alice[1] and "3101" in alice[1]["service"], alice

    # Every target is loopback: nothing is published on a public interface,
    # so the tunnel is the only way in.
    assert all("127.0.0.1" in r["service"] for r in rules if r["service"].startswith("http://")), rules

    # No two users share a port or a hostname.
    services = [r["service"] for r in rules if r["service"].startswith("http://")]
    assert len(services) == len(set(services)), services
    hosts = {r["hostname"] for r in rules if "hostname" in r}
    assert hosts == {"alice.facet.example", "bob.facet.example"}, hosts

    config = render_tunnel_config(users, tunnel_id="abc-123")
    assert "tunnel: abc-123" in config
    assert config.count("  - hostname:") == 4, config
    assert config.rstrip().endswith("- service: http_status:404"), config
    # The generated YAML must actually parse as the structure intended.
    for line in config.splitlines():
        if line.startswith("  - ") or line.startswith("    "):
            assert ": " in line, f"malformed line: {line!r}"

    # Rebuilding after a removal drops that user's rules entirely, rather
    # than leaving a hostname pointing at a port that may get reused.
    assert not any(r.get("hostname") == "bob.facet.example"
                   for r in ingress_rules(users[:1]))

    app = access_app_payload("alice", "alice@example.com")
    assert app["domain"] == "alice.facet.example"
    assert app["type"] == "self_hosted"
    assert app["http_only_cookie_attribute"] is True
    policy = app["policies"][0]
    assert policy["decision"] == "allow"
    # Exactly one address — a domain-wide include would let every colleague
    # reach every instance.
    assert policy["include"] == [{"email": {"email": "alice@example.com"}}], policy
    assert len(policy["include"]) == 1

    text = manual_instructions("alice", "alice@example.com")
    for expected in ("alice.facet.example", "cfargotunnel.com",
                     "alice@example.com", "reload cloudflared"):
        assert expected in text, expected

    print("control.cloudflare: all checks passed (ingress + access, no network)")


if __name__ == "__main__":
    demo()
